const frases = [
    "O esforço pode te levar longe, mas a preguiça já está aqui.",
    "A persistência leva ao sucesso, mas desistir é bem mais fácil.",
    "Siga seus sonhos… Ou continue no sofá, tanto faz.",
    "Se nada der certo, relaxa, amanhã pode ser pior.",
    "Trabalhe duro hoje para ter cansaço amanhã.",
    "O importante não é vencer, é evitar esforço desnecessário.",
    "Você é único, assim como todo mundo.",
    "Nada é impossível para quem já desistiu antes de tentar.",
    "Acredite nos seus sonhos, mas não se assuste quando acordar para a realidade.",
    "O tempo cura tudo, mas também estraga tudo se esperar demais.",
    "O sucesso é para poucos, e pelo visto você é muitos.",
    "Nunca deixe para amanhã o que você pode evitar para sempre.",
    "Cada dia é uma nova chance de falhar de maneira diferente.",
    "A paciência é uma virtude… Principalmente para quem não tem opção.",
    "Corra atrás dos seus sonhos! Eles correm rápido.",
    "A estrada do sucesso é longa… Melhor nem sair de casa.",
    "Seja você mesmo! Mas não crie expectativas.",
    "Trabalhe enquanto eles dormem, e durma enquanto eles aproveitam.",
    "Um dia você ainda vai olhar para trás e rir… De nervoso.",
    "O impossível só demora um pouco mais… E geralmente continua impossível.",
    "Se está difícil para você, imagina para quem realmente se esforça.",
    "Errar é humano, mas repetir o erro é especialidade sua.",
    "Desista hoje e evite a fadiga amanhã.",
    "A motivação vem de dentro… Mas a preguiça também.",
    "Quem cedo madruga… Passa o dia inteiro com sono.",
    "Se a vida te der um limão, faça uma caipirinha e esqueça os problemas.",
    "Você nasceu para brilhar… Mas esqueceram de pagar a conta de luz.",
    "O sucesso vem com o tempo… Já a preguiça é instantânea.",
    "Nunca desista dos seus sonhos! Apenas adie indefinidamente.",
    "A sorte é para poucos, mas o azar é bem democrático.",
    "Nada como um dia ruim para valorizar o dia anterior.",
    "O segredo da vida é… Bom, se eu soubesse, não estaria aqui.",
    "Seja positivo! O pior ainda pode estar por vir.",
    "A motivação é a chave… Pena que a fechadura está emperrada.",
    "Se a preguiça fosse um esporte, eu já teria várias medalhas.",
    "O melhor momento para começar foi ontem… O segundo melhor momento é amanhã.",
    "Nada como um café forte e a vontade de continuar na cama.",
    "A paciência é uma virtude… Pena que eu nasci sem ela.",
    "O impossível só leva um pouco mais de tempo… Ou nem acontece.",
    "Trabalhe duro e um dia alguém rico te notará.",
    "Dê o seu melhor! Mas se não der, finja que tentou.",
    "Seja grato pelo que tem… Porque pode ser só isso mesmo.",
    "O mundo é dos espertos… E dos que têm sorte.",
    "Se está ruim para você, imagine para quem confia em você.",
    "Nada é tão ruim que não possa piorar… Experiência própria.",
    "O segredo do sucesso? Ninguém sabe, mas todo mundo finge que sim.",
    "Siga sua intuição… Só não culpe ninguém depois.",
    "O fracasso é apenas um degrau… Para o próximo fracasso.",
    "Nunca deixe para amanhã o que você pode evitar para sempre.",
    "A estrada do sucesso é cheia de curvas… Melhor nem sair de casa.",
    "A esperança é a última que morre… Mas às vezes só finge estar viva.",
    "O importante é competir… Mas ganhar é bem melhor.",
    "Seja uma pessoa melhor… Ou não, dá na mesma.",
    "Corra atrás dos seus sonhos! Mas cuidado para não tropeçar na realidade.",
    "Seja forte! Ou pelo menos pareça ser.",
    "Um dia você ainda vai olhar para trás e rir… De desespero.",
    "A estrada do sucesso é longa… Melhor nem colocar o tênis.",
    "Persista até conseguir… Ou até cansar, o que vier primeiro.",
    "A melhor maneira de prever o futuro é esperar para ver.",
    "Cada dia é uma nova oportunidade… Para cometer erros diferentes.",
    "A realidade sempre supera a ficção… No quesito decepção.",
    "O importante não é saber, é saber quem sabe.",
    "Nada como um problema novo para fazer o antigo parecer menor.",
    "Seja otimista… Ou pelo menos finja bem.",
    "O caminho do sucesso é cheio de obstáculos… E preguiça.",
    "Nada é impossível… Apenas trabalhoso demais para tentar.",
    "Trabalhe duro e um dia você será promovido… Para outro trabalho mais difícil.",
    "O fracasso não é o fim… Mas pode ser um excelente recomeço para outro fracasso.",
    "Seja positivo! Pelo menos você ainda não foi abduzido por alienígenas.",
    "Se a vida te dá limões, pelo menos são grátis.",
    "A paciência é uma virtude… Mas a pressa é mais divertida.",
    "Nada como um dia após o outro… Para perceber que tudo continua igual.",
    "Se está difícil, imagine para quem nem tentou.",
    "Seja esperto! Mas não muito, senão vão te pedir favores.",
    "Seja você mesmo… Ou copie alguém que parece bem-sucedido.",
    "O impossível só demora mais… Ou geralmente nunca acontece.",
    "Se nada der certo, pelo menos tente parecer ocupado.",
    "Nunca desista! Só mude de ideia frequentemente.",
    "O tempo cura tudo… Mas também destrói qualquer planejamento.",
    "Viva cada dia como se fosse o último… E pague as contas como se houvesse amanhã.",
    "Não se preocupe com o futuro… Ele já está se preocupando com você.",
    "O importante é participar… Desde que você não queira ganhar."
];

console.log(frases);


const imagens = [
    'img/img1.jpeg',
    'img/img2.jpeg',
    'img/img3.jpeg',
    'img/img4.jpeg',
    'img/img5.jpeg',
    'img/img6.jpeg',
    'img/img7.jpeg',
    'img/img8.jpeg',
    'img/img9.jpeg',
    'img/img10.jpeg',
    'img/img11.jpeg',
    'img/img12.jpeg',
    'img/img13.jpeg',
    'img/img14.jpeg',
    'img/img15.jpeg',
    'img/img16.jpeg',
    'img/img17.jpeg',
    'img/img18.jpeg',
    'img/img19.jpeg',
    'img/img20.jpeg',
    'img/img21.jpeg',
    'img/img22.jpeg',
    'img/img23.jpeg',
    'img/img24.jpeg',
    'img/img25.jpeg',
    'img/img26.jpeg',
    'img/img27.jpeg',
    'img/img28.jpeg',
    'img/img29.jpeg',
    'img/img30.jpeg',
    'img/img31.jpeg',
    'img/img32.jpeg',
    'img/img33.jpeg',
    'img/img34.jpeg',
    'img/img35.jpeg',
    'img/img36.jpeg',
    'img/img37.jpeg',
    'img/img38.jpeg',
    'img/img39.jpeg',
    'img/img40.jpeg',
    'img/img41.jpeg',
    'img/img42.jpeg'
];

function gerarFrase() {
    const indiceFrase = Math.floor(Math.random() * frases.length);
    const indiceImagem = Math.floor(Math.random() * imagens.length);

    document.getElementById("frase").innerText = frases[indiceFrase];
    document.getElementById("imagem").src = imagens[indiceImagem];
}

window.onload = gerarFrase;
